# Generated by Django 3.1 on 2023-01-04 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^[6-9]\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('USER', 'USER'), ('EMPLOYEE', 'employee'), ('CUSTOMER', 'customer')], default='USER', max_length=8, verbose_name='User Type'),
        ),
    ]
